#!/usr/bin/env python3
"""
Generate Instagram post images from a prompts.json file.

Usage:
    python scripts/generate_instagram_images.py <prompts.json>

The prompts.json should be generated by the Claude skill and contain:
{
    "output_dir": "data/clients/ardona/images/2026-03-30",
    "images": [
        {
            "filename": "mon-instagram-automation-case-studies.png",
            "prompt": "Create a professional Instagram post image..."
        },
        ...
    ]
}
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.image_gen import get_genai_client, generate_image

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/generate_instagram_images.py <prompts.json>")
        sys.exit(1)

    prompts_path = Path(sys.argv[1])
    if not prompts_path.exists():
        print(f"Error: {prompts_path} not found")
        sys.exit(1)

    data = json.loads(prompts_path.read_text())
    output_dir = Path(data["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    images = data["images"]

    print(f"Output: {output_dir}")
    print(f"Images to generate: {len(images)}")

    client = get_genai_client()
    generated = 0

    for i, item in enumerate(images):
        filename = item["filename"]
        prompt = item["prompt"]
        output_path = output_dir / filename

        if output_path.exists():
            print(f"  [{i+1}/{len(images)}] Skipping {filename} (exists)")
            generated += 1
            continue

        print(f"  [{i+1}/{len(images)}] Generating: {filename}...")
        if generate_image(client, prompt, output_path):
            print(f"           ✓ Saved")
            generated += 1
        else:
            print(f"           ✗ Failed")

    print(f"\nDone! {generated}/{len(images)} images generated.")
    print(f"Output: {output_dir}/")


if __name__ == "__main__":
    main()
