#!/usr/bin/env python3
"""
Generate ad creative images from a prompts.json file.

Usage:
    python scripts/generate_ad_creatives.py <prompts.json>

The prompts.json should be generated by the Claude skill and contain:
{
    "output_dir": "data/clients/ardona/ad-creatives/2026-03-30-offer-slug",
    "brief": "# Ad Creative Brief\n...",
    "variations": [
        {
            "folder": "variation-1-pain-point",
            "copy_md": "# Ad Variation: Pain Point\n...",
            "images": [
                {
                    "filename": "feed-ad.png",
                    "prompt": "Create a professional square ad image..."
                },
                {
                    "filename": "story-ad.png",
                    "prompt": "Create a professional vertical ad image..."
                }
            ]
        },
        ...
    ]
}
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.image_gen import get_genai_client, generate_image


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/generate_ad_creatives.py <prompts.json>")
        sys.exit(1)

    prompts_path = Path(sys.argv[1])
    if not prompts_path.exists():
        print(f"Error: {prompts_path} not found")
        sys.exit(1)

    data = json.loads(prompts_path.read_text())
    output_dir = Path(data["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save brief
    if data.get("brief"):
        (output_dir / "brief.md").write_text(data["brief"])
        print("✓ brief.md")

    variations = data.get("variations", [])
    if not variations:
        print("No variations to generate.")
        return

    client = get_genai_client()
    total_images = 0
    total_expected = 0

    for v in variations:
        folder = v["folder"]
        var_dir = output_dir / folder
        var_dir.mkdir(parents=True, exist_ok=True)

        # Save copy
        if v.get("copy_md"):
            (var_dir / "copy.md").write_text(v["copy_md"])

        images = v.get("images", [])
        total_expected += len(images)

        for item in images:
            filename = item["filename"]
            prompt = item["prompt"]
            output_path = var_dir / filename

            if output_path.exists():
                print(f"  [{folder}] Skipping {filename} (exists)")
                total_images += 1
                continue

            print(f"  [{folder}] Generating {filename}...")
            if generate_image(client, prompt, output_path):
                print(f"    ✓ Saved")
                total_images += 1
            else:
                print(f"    ✗ Failed")

    print(f"\nDone! {total_images}/{total_expected} images across {len(variations)} variations.")
    print(f"Output: {output_dir}/")


if __name__ == "__main__":
    main()
