#!/usr/bin/env python3
"""
Repurpose content: generate platform-specific images from a prompts.json file,
and save pre-generated text files.

Usage:
    python scripts/repurpose_content.py <prompts.json>

The prompts.json should be generated by the Claude skill and contain:
{
    "output_dir": "data/clients/ardona/repurposed/2026-03-30-blog-title",
    "text_files": {
        "source.md": "original blog content...",
        "instagram-post.md": "# Instagram Post\n...",
        "instagram-story.md": "...",
        "linkedin.md": "...",
        "facebook.md": "..."
    },
    "images": [
        {
            "filename": "instagram-post.png",
            "prompt": "Create a professional Instagram post image..."
        },
        {
            "filename": "instagram-story.png",
            "prompt": "Create a professional Instagram Story image..."
        },
        {
            "filename": "facebook.png",
            "prompt": "Create a professional Facebook image..."
        }
    ]
}
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.image_gen import get_genai_client, generate_image


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/repurpose_content.py <prompts.json>")
        sys.exit(1)

    prompts_path = Path(sys.argv[1])
    if not prompts_path.exists():
        print(f"Error: {prompts_path} not found")
        sys.exit(1)

    data = json.loads(prompts_path.read_text())
    output_dir = Path(data["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save text files
    text_files = data.get("text_files", {})
    if text_files:
        print(f"Saving {len(text_files)} text files...")
        for filename, content in text_files.items():
            (output_dir / filename).write_text(content)
            print(f"  ✓ {filename}")

    # Generate images
    images = data.get("images", [])
    if not images:
        print("No images to generate.")
        return

    print(f"\nGenerating {len(images)} images...")
    client = get_genai_client()
    generated = 0

    for i, item in enumerate(images):
        filename = item["filename"]
        prompt = item["prompt"]
        output_path = output_dir / filename

        if output_path.exists():
            print(f"  [{i+1}/{len(images)}] Skipping {filename} (exists)")
            generated += 1
            continue

        print(f"  [{i+1}/{len(images)}] Generating: {filename}...")
        if generate_image(client, prompt, output_path):
            print(f"           ✓ Saved")
            generated += 1
        else:
            print(f"           ✗ Failed")

    print(f"\nDone! {generated}/{len(images)} images + {len(text_files)} text files.")
    print(f"Output: {output_dir}/")


if __name__ == "__main__":
    main()
